### ISSUE TITLE
About Topic

### ISSUE THREAD

**Issue by JSY8869** [JSY8869/Us-su#1]
# Topic
## 사용할 기술
영상 or 이미지, 딥러닝 활용할 것
센서
완전 소프트웨어
## 정세영
- ~배달 음식을 문 앞에 배달했을 때 핸드폰으로 알림을 주는 어플 or 알림 기능을 하는 무언가~
- ~집 주인을 위한 세입자들의 불만을 처리하고, 월세 확인 및 관리를 도와주는 어플, 홈페이지~
## 박지수
- ~물류공장 피킹 로봇~
- ~자신의 글꼴을 만들고 사용할 수 있는 소셜 네트워크~
- ~손글씨를 재현하여 매년 가족과 친구들에게 크리스마스 카드를 자동으로 보내는 AI~
- ~디자이너와 개발자가 파트너쉽을 위해 서로 프로젝트를 발표할 수 있는 웹사이트~
- ~지역 비즈니스를 위한 커뮤니티 플랫폼. (오너들은 통찰력(정보?)을 공유하고, 틈새시장이나 프랜차이즈에서 사업을 성장시키는 방법에 대한 강좌를 판매할 수 있음)~
## 박소현
- 지수 의견 + 손글씨나 싸인을 비교 할 수 있는 소셜 네트워(필적 확인)
- 식사메뉴 추천해주는 소셜 네트워크 (사용자의 입력값에 따라 싫어하는 것, 전날 먹은 것 등을 제외해 추천) 
- 스마트 냉장고
-(냉장고 안에 있는 음식들의 유통기한을 일일이 보기 어렵다. 스마트 냉장고를 이용해 음식을 효율적으로 관리할 수 있음.
사용할 수 있는 기술-1. 이미지센서: 제품들의 유통기한을 인식해 데이터에 저장한다. (제품의 바코드 인식)
2. 앱- 제품들의 유통기한을 확인할 수 있고, 기한이 다가온 음식들은 알림을 통해 사용자에게 알려줌.
<시중에는 바코드를 수동으로 사진찍어 관리 앱을 사용하는데 이 아이디어는 냉장고에 제품을 바코드가 잘 보이게 놓아두면 알아서 바코드가 센서를 통해 인식돼 자동으로 앱에 저장되게 된다.>
## 이수혁
-  지하철역에 설치되어있는 스크린도어 같이 횡단보도 혹은 기차역에 스크린도어와 같은 사고 방지 장치를 설차한다.
-  화재가 났을때 어느 위치에서 불이 났는지 알려주는 시스템

**Comment by fora22** [comment]
안녕하세요 ㅎㅎ

@JSY8869 가 만들었다 해서 놀러왔다가, 아이디어(Topic) 제시하는 것 같길래, 이전부터 생각해오던 아이디어 하나를 공유하려 합니다.

# 다나와 처럼 NGO, NPO 를 한 눈에 볼 수 있도록 만들어 주는 사이트
## 취지(생각하게된 이유)
- NGO 혹은 NPO에 기부나 후원을 할려고 하면 알아볼 수 있는 방법은 TV의 광고나 본인의 직접검색밖에 없다.
- NGO, NPO 도 종류가 엄청 많고(환경, 노숙자 도움, 노동자, 어린이, 불치병 등) 종류에 따른 단체도 매우 많다.
- 하지만 이 단체들을 비교(자신이 믿는 가치의 후원을 위해서)해보기 위해서 직접 검색 등으로 인해 시간이 많이 들고 힘들다.
  - 이 때문에 중간에 포기하는 경우도 많다.

## 따라서 
- [다나와](http://danawa.com/) 같이 필터링을 통해 자신이 원하는 NGO, NPO 단체가 나오도록 웹페이지를 만든다.
### 구체적으로는
![image](https://user-images.githubusercontent.com/48875566/103288853-2f24fd80-4a29-11eb-913a-e02d7c65de69.png)
- 인스타 그램같이 후원단체 대표 사진이 갤러리 형태로 뜨게함
- 사진 밑에는 간단한 설명 혹은 키워드 넣기
- 페이지 상단에는 다나와같이 검색 필터링 기능을 넣음
- 사진을 클릭하면 단체 홈페이지로 이동하도록 링크 걸어놓음

# 이미지 출처
- https://m.blog.naver.com/designpress2016/221438028724

**Comment by JSY8869** [comment]
# 한쪽 청각 장애인을 위한 소리 방향 알리미
## 생각한 이유
- **현재 대한민국에서 한쪽 청각을 잃은 경우, 다른 한쪽이 정상이라면 청각 장애인이 아니다.**
- 하지만 한쪽 청각이 없을 때의 불편함은 사실이다.
- 장애인으로 인정받지 못하는 분들을 위해 도움이라도 주고 싶다.
- [청각장애 범위를 넓혀주세요](https://www1.president.go.kr/petitions/209600) 국민청원
## 기술 설명
- 오른쪽 청력을 잃은 경우 청력은 없어도 촉각은 있기 때문에 이를 이용한다.
- [아두이노의 소리 감지센서를 사용한다.](https://wikidocs.net/91343)
- 구조에 관해서는 아직 구상중...
- 왼쪽과 오른쪽의 소리를 비교하여 오른쪽의 소리가 더 큰 경우 진동으로 알려준다.
- 소리는 왼쪽 귀로 듣지만 진동을 통해 방향을 알 수 있다.

**Comment by JSY8869** [comment]
# 시각장애인을 도와주는 안내견 전용 블랙박스
## 생각한 이유
- 최근 발생했던 안내견의 출입을 막는 매장들의 문제
- 안내견에 대한 잘못된 행동에 대한 주의사항 전파
- 사고 및 사건 발생 시 그에 대한 녹화자료의 필요성
- 안내견이 실제로 느끼는 위협과 안내견에 대한 사람들의 행동에 관한 연구 자료의 필요성
## 기술 설명
- 안내견의 몸줄에 장착되어 주변을 녹화한다.
- 리모컨을 통해 or 음성인식을 통해 시각장애인 대신 필요할 때 주의사항을 말해주는 장치
- 안내견을 쓰다듬거나 만지려는 행인에 대해 자동으로 주의를 전하는 기술(영상 처리 기술)

**Comment by parkwltn** [comment]
# 스마트팜 폐사체 검출 및 감시 시스템(축산)
## 배경
### 스마트팜이란?
농작물과 가축의 생육정보와 환경정보 등에 대한 정확한 데이터를 기반으로 언제 어디서나 농작물과 가축의 생육환경을 점검하고, 적기에 처방함으로써 노동력·에너지·양분 등을 종전 보다 덜 투입하고도 농산물의 생산성과 품질제고가 가능한 농업
### 필요성 및 기대효과
(넓은) 농·축산업인구 고령화, 젊은층의 영농승계 인력난 및 생산면적 감소, 투자위축 등에 따른 소득·수출·성장률 정체 등 지속가능성 위기에 처한 농촌문제 해결안
(좁은) 질병위험요소 사전차단, 생산량 예측
## 설명
실시간 영상 정보(열화상 카메라, 적외선 센서)를 이용하여 평균 체온보다 훨씬 낮은 체온의 대상 검출 → 서버로 전달 → 앱 알림
#### 축사 기자재 및 환경관리
실시간 영상, 실시간 센서, 상시 안전감시, 축사 에너지 모니터링
#### 사양관리 기자재
폐사체 검출 및 감시
## 대상
양돈, 소, 양계 등
## 비슷한 어플리케이션
스마트폰으로 정상 보다 높은 체온을 가진, 고열의 돼지를 찾을 수 있는 어플리케이션 [Degree2act](https://www.degree2act.com/intro/)
Degree2act는 내가 스마트폰을 들고 돼지에게 일일이 비춰야 함.
## 참고문헌
스마트팜 기술 및 시장동향 보고서
[인공지능 학습용 데이터 구축 사업 주요 분야별 중장기 로드맵](https://aihub.or.kr/node/12099)

### 1.16 추가
#### 열로 검출할 수 있는 병(돼지) - 고온 증상
붉은 피부병, 돼지 연쇄상구균병, 돼지 번식 및 호흡장애 종합증, 톡스플라즈마병, 돼지 출혈성패혈증, 돼지열병

**Comment by park-sohyeon** [comment]
# 신체온도 인식을 통한 냉난방기 온도 조절 시스템(지수 의견 참고)

## 설명

보통 냉난방기는 실내 온도를 조절하여 온도를 조절한다. 더 나아가 사람의 신체 온도를 열화상 카메라와 적외선 센서, 아두이노를 사용하여 사용자에게 알맞은 온도를 제공한다. 

1. 열화상 카메라와 적외선 센서를 사용해 사용자의 체온을 측정
2. [아두이노 손가락 심장박동 감지 센서](https://gent.tistory.com/73) (KY-039) 를 사용하여 심박수를 체크해 일정 수준보다 심박수가 낮으면 추움, 높으면 더움을 체크해 서버로 정보 전달
3. 더울 때(부채질을 한다거나 땀을 흘림, 숨가쁨), 추울 때(손을 비비거나 몸의 떨림 감지)의 특별한 행동을 이미지 인식을 이용하여 체크해 서버로 정보 전달

#### 체온만으로는 추움과 더움을 인지하는 것이 부정확하기에 심박수, 특정 행동 데이터까지 추가해 온도조절을 도움.

### 비슷한 기능
1. 현재 시설에 설치되어 있는 얼굴 인식 체온 측정기 (체온 알림)
2. 웨어러블 기기 (심박수 알림)

**Comment by parkwltn** [comment]
# '지문자' 교육 게임 어플리케이션
## 용어
수어(수화) : 청각장애인(농인·聾人)들이 손의 움직임, 얼굴 표정, 몸짓으로 의사를 표현하는 시각언어.
지문자 : 한글, 알파벳 등의 문자를 수어로 표현한 것. 수화만으로는 이름이나 지명과 같은 고유명사 정보를 주고받을 수 없기에 종종 지문자가 함께 사용됨.
## 필요성
농인들이 사용하는 언어인 수어를 대부분의 비장애인들이 전혀 알지 못하는 현실. 모든 사람이 수화에 능통할 수는 없겠지만 지문자만이라도 익혀 둔다면 청각장애인과 소통이 필요할 때 유용하게 사용할 수 있을 것.
## 대상
수어를 배우고 싶은 청인들
## 설명
### 1. 학습하기
지문자 ㄱ 보여주고 사용자가 손모양 따라함. 일치하면 띵동 소리나면서 다음 ㄴ ㄷ ㄹ 순서대로 계속.
### 2. 테스트
1. 단어를 지문자로 표현하기
화면에 단어 표시
사용자가 손모양으로 지문자를 표현하면
사용자의 손모양을 인식
![1](https://user-images.githubusercontent.com/67677312/105039607-1b0e7200-5aa4-11eb-84d0-e45c3910b892.jpg)
2. 지문자를 읽고 단어 입력하기
화면에 지문자 표시
지문자를 읽고 해당 단어를 입력
![2](https://user-images.githubusercontent.com/67677312/105039623-1ea1f900-5aa4-11eb-9447-fd1dce4e0c6a.jpg)
3. 점수 적립
1, 2 진행 과정에서 정답일 시 걸린 시간을 측정하여 점수 적립
## 기대 효과
수어에 대한 관심을 높이고 즐겁게 배울 수 있게 함.
## 우려되는 점
지문자는 한글을 손모양으로 나타낸 것으로 익혀야 할 수가 많지 않아 일회성으로 사용될 수 있음.
## 개선방안
1. 지문자 2. 단어 3. 짧은 문장 등으로 난이도 설정
## 비슷한 어플리케이션
[수화](http://sgwga.or.kr/bbs/board.php?bo_table=B23&wr_id=307)
동작 인식 기능을 이용하여 수어를 실시간으로 번역해주는 앱
카메라가 수어를 실시간으로 인식하여 텍스트로 번역해주어 소통을 원활하게 한다.

**Comment by JSY8869** [comment]
# 우리아이 화재탈출 넘버원!
## 필요성
화재 발생 시 아이의 안전을 지키고, 판단이 어려운 미취학 아동들의 탈출 경로 및 주의사항 안내
## 대상
화재 발생 시 대피해야 하는 어린이
## 설명
- 헬멧에 카메라를 작착한 형태로 사용.
- 화재 발생 시 헬멧에 의한 낙하물 피해 방지
- 카메라의 영상을 통해 문, 계단, 연기, 화재등을 영상처리를 통해 인식
- 음성으로 주의사항 전파 및 탈출경로 안내
- 가능하다면 화재진원지의 정보를 전달받아 해당 지역을 피해서 대피하는 경로를 안내
## 기술
- 영상처리(OpenCV)
## 해결해야 할 것
- 화재진원지와의 연결은 화재 감지기까지 개발할 필요가 있어짐(어렵진 않아보임)
- 화재의 연기로 인해 시야가 차단된 경우 작동이 힘들 것으로 보임
- 실제 화재 발생 시 자세를 낮추고 가기 때문에 카메라의 각도의 문제

**Comment by park-sohyeon** [comment]
# 어린이 주방 사고 지킴이 

## 필요성
어른들이 집을 비운 사이 어린이들이 주방에서 요리를 하거나, 장난을 쳐 화재사고가 빈번이 발생함. 

## 대상
어린이 화상사고의 대부분이 만 6세 이하 영유아에 발생하지만 크게 범위를 확대해 만 14세 이하 어린이까지.

## 설명
1. 주방에 사각지대가 생기지 않게 3,4개의 캠을 설치해 zone을 구성.
2. 영상처리를 이용해 어린이가 주방에 들어오자마자 영상이 녹화가 되며 바로 어른들에게 핸드폰으로 알람이 감.
3. 가스레인지 등 주방기구를 건드리는 행동을 인식하면 경고음을 울림.
4. 열이나 연기가 감지되거나 아이의 데시벨이 일정 수준을 넘어 높은 경우 어른들에게 알람 및 신고 기능 작동.

**Comment by su-hyeok** [comment]
# 주차구역확인하기 

## 필요성
대형마트 혹은 백화점을 가보면 항상 장애우 혹은 여성 저용주차 공간이 있기 마련, 그러나 그 공간이 주차되어있는지는 가보지 않고서는 알수가 없다. 따라서 주차공간을 알려주는 웹 혹은 앱을 만들어 놓으면 몸이 불편한 사람이 대기열 없이 주차를 할 수 있다.

## 대상
운전을 하는 장애우분들

## 설명
1. 주차장 도면을 본떠 하나의 웹 혹은 앱을 만듬
2. 사용자가 현재 주차공간이 얼마나 확보가 되어있는지를 실시간으로 확인해 붐비는 시간인지를 확인한다.
3. 사용자가 원하는 시간에 일을 볼수 있게 도와주는 효과가 있다.

## 개선방향
장애우분들만이 아닌 일반사람들에게까지 전달하여 사람이 붐비는 혼잡한 상황을 피할 수 있음.

**Comment by JSY8869** [comment]
## MBTI에 따른 스트레스 해소 및 학습 방법 추천, 관리 어플리케이션

### 필요성
자신의 성격 유형에 따른 스트레스 해소 수단 및 학습 방법을 자기 객관화가 힘든 사람들에게 추천해 줄 수 있고, 지속적인 관리를 통해 삶의 질을 높여준다.

### 요약
- 사용자의 MBTI를 입력 받고 설문을 통해 스트레스 정도를 측정한다.
- 성격유형과 스트레스의 정도에 맞춰 스트레스 해소 방법을 추천해 주며 이를 수행할 경우 보상을 주는 시스템
- 성격유형에 따라 선호하는 학습 방법이 다른데 이에 따라 학습 방법을 추천해주고 학습 시간 및 학습 수단, 학습량을 관리해주는 프로그램
- MBTI에 따라 달라지는 여러가지 특징들이 있기 때문에 추가할 수 있는 기능은 많다고 생각함

### 장점
- 자기 객관화가 힘든 사람들에게 자신에게 가장 어울리는 스트레스 해소 수단과 학습 방법을 알게 해줄 수 있음
- 딥러닝을 사용하지 않고 만들 수 있음

### 단점
- 심리학 지식이 필요함
- 설문조사를 진행해야 할 필요가 있음

### 참고 자료
- [MBTI에 따른 학습 방법 관련 논문](http://scholar.dkyobobook.co.kr/searchDetail.laf?barcode=4050025333720#)
- [MBTI에 따른 스트레스 정도 및 해소 방법 논문](http://crins530.jnuac.kr/bbs/board.php?bo_table=journal2&wr_id=184)
- [MBTI에 따른 학습 방법 관련 자료](https://www.kci.go.kr/kciportal/ci/sereArticleSearch/ciSereArtiView.kci?sereArticleSearchBean.artiId=ART002562104)

**Comment by parkwltn** [comment]
# 발달장애아동의 듣기 능력 향상을 위한 프로그램
응용행동분석(ABA) 치료 기법 중 언어행동을 고려함
### 필요성
ABA 치료 과정이 치료사(제 3자) 없이 진행 가능하다.
### 요약
1. '여기 보세요'라고 말한 후 응시할 포인트 제시(캠 근처로)
2. ‘따라해 보세요’라고 말한 후 이어 모방할 표정 제시 : 웃는, 화난, 슬픈 표정 등
3. ‘따라해 보세요’라고 말한 후 이어 모방할 동작 제시 : 손뼉치기, 포인팅, 일어서기, 한바퀴 돌기, 앉기, 머리문지르기, 입 두드리기 등(주의 : 말은 ‘이렇게 해보세요’이지 ‘손뼉쳐 보세요’가 아님)

아이에게 위와 같은 과제를 제시하고 수행하면 보상 제공
과제 수행 여부는 캠을 통해 판단함(예: 웃는 표정 인식 > 성공)
### 대상
- ​​학습에 어려움을 겪는 아동
- ​​새로운 기술을 습득하는데 어려움을 겪는 아동
- ​​의사소통에 어려움을 겪는 아동

**Comment by su-hyeok** [comment]
## 악보프로그램

### 대상
클래식피아노를 사용하는 모든 대상

### 설명
클래식 피아노의 경우 악보를 펼칠 수 있는 공간이 존재한다. 악보집을 들고 다닐 필요 없이 네비게이션 같은 화면으로 원하는 악보를 추출하여 악보처럼 볼수 있게한다. 
즉 악보집과 피아노를 합친다는 개념으로 볼 수 있다.
 ### 장점
1. 악보를 들고 다닐 필요가 없어 환경 친화적이다
2. 원하는 악보를 언제든 꺼내볼수 있기에 상당히 편리하다.
3. 피아노 어플에 있는 기능등을 활용하여, 초심자들에게 이용하기 편리하게 할 수 있다. 
4.  악보와 더불어 https://www.youtube.com/watch?v=MUk39sU4C14 이 영상에서 보이는 것과 같은 영상을 추가한다면 배우는 입장에서는 악보만 볼때 보다 친숙하여 더 빠르게 곡을 완성할 수 있다.

### 생각해 볼 것
1.클래식 피아노라는 악기에 네비게이션 같은 전자기기(?)를 접목 시킬 수 있는가
2. 접목시킨다 하여도 들리는 소리에 문제가 없는가
### 이미 있는 것인가
https://www.hankookilbo.com/News/Read/201907281641031003 위의 기사처럼 태블릿 같은 곳에 담아두는 경우는 있지만 피아노랑 결합되어있는것은 보지 못함.

### 문제
https://m.blog.naver.com/PostView.nhn?blogId=kelly3330&logNo=221178004616&proxyReferer=https:%2F%2Fwww.google.com%2F 이미 전자악보가 활성화되어있음
개선하려면 음표를 한글로 나타내는 작업이 필요할듯 보임

**Comment by JSY8869** [comment]
# 감정인식 실시간 수어 번역 통화 어플리케이션
## 대상
1. 농인
2. 수어를 모르지만 농인과 대화를 원하는 청인
3. 수어를 배우고자 하는 사람
## 설명
- 영상통화를 통해 대화를 진행함
- 설정 화면에서 본인이 농인인지 청인인지 선택
- 설정 화면에서 본인이 수어를 할 수 있는지 못하는지 선택
- 영상통화 진행 시 본인이 설정한 본인의 정보에 따라 작동함
- 통화 중 얼굴의 표정을 인식하여 감정상태를 보여줌(불필요시 제외)
### 사용자가 농인인 경우
- 상대방이 수어를 못 하는 청인인 경우
   -  상대방이 하는 말을 인식하여 글로 보여줌
- 상대방이 수어를 할 수 있는 경우
   -  상대방의 수어를 실시간으로 번역하여 글로 보여줌
### 사용자가 청인인 경우
- 상대의 수어를 실시간으로 번역하여 글로 보여줌
- 상대도 청인인 경우는 제외함(필요성 x)
## 장점
- 31,440개의 동영상으로 얻어낸 데이터를 구할 수 있음
- 수어를 모르는 사람도 농인과 대화를 할 수 있다.
- 수어를 모르는 사람도 대화를 통해 쉽게 공부할 수 있다.

## 생각해 볼 것
1. 어플리케이션을 만들 수 있는가?
2. 데이터가 있지만 이를 어떻게 딥러닝 모델로 만들 것인가

## 예상되는 사용 기술
- python의 딥러닝 (수어 인식)
- OpenCV 영상인식
- REACT.JS 웹 or 앱 개발]
- DB
- AWS 서버

## 참고자료
- [OpenCV와 딥러닝을 활용한 감정인식](https://m.blog.naver.com/roboholic84/221633210887)
- [수어 데이터셋](https://aihub.or.kr/keti_data_board/language_intelligence)

**Comment by park-sohyeon** [comment]
# 치매예방 프로그램
## 대상
치매를 예방하기 위한 나이층. 주로 50대 이상

## 설명
: 치매 발병율이 점점 늘어나고 예방하기 위한 방법 필요. 그렇기에 치매를 예방하기 위한 앱 생각. 예방을 하기 위해서 이 앱이 필요함.

- 앱을 처음 들어갔을 때 1. 단순 수학 계산(사칙 연산), 2. 단순 문장 구성관련 퀴즈, 3. 일기장, 4. [카드 짝 맞추기](https://chaospace.tistory.com/247) 5. [끝말잇기](https://blog.naver.com/jsk6824/221950695920) 목록이 나옴.
- 각 1,2.3,4,5 을 사용자가 진행하도록 하며 사용자가 푼 결과값을 통해 지난 기록들과 계속 비교.
 
일기장 이란??

- 최근 일을 잘 기억하지 못하는 치매의 특성을 이용하여 하루에 일어났던 일을 줄 글로 쓰게 한 뒤 키워드를 뽑아 하루 뒤에 퀴즈로 물어봄.

_예를들어 "나는 오늘 바나나를 먹었다. 오늘 가족들과 만나 저녁을 함께 먹었다." 라고 어제 기록. 오늘 앱을 열었을 때 퀴즈 형식으로 "어제 저녁을 누구와 먹었나요?" 라고 퀴즈가 나온다면 답을 가족으로 택하게끔._

## 장점

- 치매 예방을 위한 프로그램들이 모여있어 한 번에 결과를 정리해서 보기 쉬움

## 예상되는 사용 기술

- 오픈소스 gpt3 사용(수학, 언어적 부분)
- DB
- 웹
- 서버

## 생각해 볼 것
- 게임은 더 넣을 수 있음.
- 치매율을 계산해 결과로 딱 보여줄 수 없음 - 정확한 치매율 데이터가 없기 때문.

**Comment by JSY8869** [comment]
# [아이디어 결정!](https://github.com/JSY8869/Us-su/issues/1#issuecomment-778320256)
