### ISSUE TITLE
프로토타입 초안입니다!

### ISSUE THREAD

**Issue by parkwltn** [JSY8869/Us-su#102]
[프로토 v1](https://ovenapp.io/view/oXD3mchMAAA5Alffv8ijbyYyEE0njXtP/sBVfp)
[참고](https://user-images.githubusercontent.com/67677312/117548313-44f99d80-b06f-11eb-881d-a8febd121e7c.jpg)

**Comment by JSY8869** [comment]
너무 멋져....
