### ISSUE TITLE
15th Meeting Review

### ISSUE THREAD

**Issue by parkwltn** [JSY8869/Us-su#106]
## NLP
@JSY8869 
- keras 정리
- 코드 분석중 30%

@su-hyeok 
- 새 domain 생성중

### 데이터 전처리
@JaeHong-Ahn

## Server
@park-sohyeon 
- 플라스크 생성
- 프로젝트 생성
- 웹페이지 띄움

## UI
@zsueue 
#### [프로토타입 v1](https://ovenapp.io/view/oXD3mchMAAA5Alffv8ijbyYyEE0njXtP/sBVfp)
- 설정 X, 결과 △, 뒤로 가기 X
#### 개발
- 로딩
- 메인

**Comment by JSY8869** [comment]
오.... 내가 올리려고 들어왔는데 고맙당~~
