### ISSUE TITLE
markdown 작성을 위한 팁

### ISSUE THREAD

**Issue by fora22** [JSY8869/Us-su#15]
여러분 Github에 문서작성(?)을 위해서는 마크다운 문법(?)을 활용하는게 아마 편할 겁니다. 문법에 대해서는 많은 포스트가 있지만 어디서 작성해야하는지 모르실 것 같아서 한 번 작성해봤습니다.

# 1. Visual Studio Code 활용
- [공식 홈페이지](https://code.visualstudio.com/)

vscode는 제가 많이 사용하는 코드 편집기인데(IDE가 아닙니다) markdown 문법으로 문서를 작성할 때도 많이 사용합니다.

vscode가 좋은 이유는 Winodws, macOS, Linux 어디서든 사용할 수 있다는 점과 다양한 코드 편집 기능 뿐만 아니라 넓은 Extensions(확장) 생태계가 있습니다.

Extensions은 vscode 기본적인 기능 이외에도 사람들이 필요할만한 기능을 직접 만들어서 배포하는 플랫폼(?)입니다. 크게는 컴파일러로 코드가 실행되게 도와주기도 하고 작게는 괄호짝이 맞도록 괄호에 색깔을 입혀주기도 하죠([코드 하이라이팅](https://developer-theo.tistory.com/entry/VSCode-%ED%99%95%EC%9E%A5-%EB%8F%84%EA%B5%AC-%EB%8D%B0%EC%BD%94%EB%A0%88%EC%9D%B4%EC%85%98-%ED%8E%B8)).

![image](https://user-images.githubusercontent.com/48875566/103469590-1b232800-4daa-11eb-88c6-839be0b3c18b.png)

vscode는 기본적으로 마크다운을 지원해줍니다. 아무 폴더에 가서 `{파일이름}.md`파일을 만들면 마크다운 파일이 만들어집니다. 거기서 오른쪽 위를 보면 `open preview to the side` 버튼이 있습니다. 버튼을 누르면 마크다운 문법이 적용된 문서를 볼 수 있는데 아래 그림처럼 왼쪽에는 마크다운 원본, 오른쪽에는 적용 문서를 보며 작성할 수 있습니다.

![image](https://user-images.githubusercontent.com/48875566/103469186-df399400-4da4-11eb-9278-5c7ca3064775.png)

마크다운에 대한 Extensions 도 있는데 이것을 사용하면 마크다운 문법을 자동완성해줍니다. `ctrl + shift + x`를 눌러서 Extensions 창에 간 다음 검색창에 `Markdown All in One`을 친 다음 install 하면 자동으로 설치 됩니다. 설치 후 vscode를 껐다가 다시 키면 적용됩니다(vscode의 Extensions 대부분이 그렇습니다). 그러면 손쉽게 markdown 문서를 작성할 수 있습니다.

# 2. Typora

- [공식 홈페이지](https://typora.io/)

타이포라는 vscode로 작성하기 전에 제가 쓰던 마크다운 편집기(뷰어) 프로그램입니다.

마크다운 문법에 맞춰 작성하면, 바로 서식이 적용되고 무료 서비스라서 쉽게 사용 가능합니다. 2020년 3월 기준으로 macOS, Winodws, Linux 3가지를 지원합니다. 설치는 그냥 프로그램 다운 후 설치 마법사의 지시를 따라 설치를 진행하면 됩니다. 잘 모르겠으면 구글에 검색하기 바랍니다.

Typora는 Markdown 문법만 알고 있으면 손쉽게 작성할 수 있고 문서도 간결하고 이쁘게 보여주는 대신 약간의 단점이 있습니다.

## 1. 원본 내용과 서식이 적용된 내용을 동시에 볼 수 없습니다.
예를 들어 '# 제목'을 하고 싶었지만 '## 제목'을 쓴 경우, Typora는 헤딩2가 적용된 '제목'만 보여주기 때문에 나중에 문서가 많이 작성되면 혼란을 불러일으킬 수 있습니다.
## 2. Github와 문법이 아주 약간 다르다.
크게 신경쓸 일은 아니지만 Markdown에도 여러 가지 버전에 따라 문법이 바뀌기도 합니다. [Github Markdown](https://guides.github.com/features/mastering-markdown/)이 Github에서 사용되는 Markdown인데 Typora 조금 다른 점이 있습니다(Typora에서 작성한 후 Github에 붙여넣기 하면 내가 의도한 서식이 나오지 않을 수도 있다). 

물론 크게 다른것도 없고 2019년에 달랐던 것이니 최근에는 바뀌었을 수도 있으니 참고하기 바랍니다.

# 3. 온라인 사이트
마크다운을 온라인에서 작성할 수 있는 사이트도 있습니다. 바로 [StackEdit](https://stackedit.io/)입니다. 저는 사용하진 않아봤지만 검색 결과 많은 사람들이 초심자에게 추천하고 있습니다(다른 사이트도 많습니다.).

문서도 깔끔하고 무료로 이용할 수 있어서 좋습니다. 인터넷이 있다면 어디에서나 접속할 수 있고, 구글 계정을 통해 구글 드라이브에 저장하거나 Dropbox, WordPress, Google Blogger 등과 연결할 수 있습니다. Github 계정과도 연결할 수 있다고 하니 좋은 점은 많지만 **기본적으로 외국 사이트라서 모든 설명이 영어로 되어 있으니 참고하시기 바랍니다.**

# 저는 어떻게 하냐면
![image](https://user-images.githubusercontent.com/48875566/103469814-101dc700-4dad-11eb-876d-833006dd5db1.png)

저는 보통 바탕화면 아이콘을 많이 두지 않도록 하는 편입니다(바탕화면 아이콘이 많으면 컴퓨터 키는 속도(부팅 속도)가 느려짐 -> 얼마나 느려질지는 모름). 

그래서 잠깐 읽어볼 pdf 파일이나 카톡 공지방에 올라는 문서 파일 같은, 보고 지워버릴 파일들은 전부 바탕화면의 `Trash Room`이라는 폴더에 넣어 놓습니다. 일종의 바탕화면 역할을 하는 셈이죠. 

그리고 휴지통을 제외한 딱 하나 파일만 바탕화면에 두는데 `Note.md` 파일입니다. 여기서 Github에 올리는 문서(README.md, Wiki)나 Issue, PR에 대한 답변을 작성합니다. 그리고 내용을 복붙해서 올리죠.

이미지 같은 경우에는 Github의 Issue 댓글 칸 같은 곳에 가서 이미지를 붙여 넣으면 온라인 링크를 만들어주는데 그 링크를 활용합니다. 자세한 것은 [링크](https://worthpreading.tistory.com/83) 참조.

# 결론적으로..
아무튼 제 하는 방법과 상관없이 1,2,3 중에 취향대로 하시면 됩니다. 어떤 것도 다 좋습니다.

# Reference
- [Markdown 온라인 에디터](https://statnmath.tistory.com/157)
- [Github Readme에 이미지 올리기](https://worthpreading.tistory.com/83)

**Comment by JSY8869** [comment]
좋은 팁 감사합니당~~ wiki에 추가해도 될까요??

**Comment by fora22** [comment]
> 좋은 팁 감사합니당~~ wiki에 추가해도 될까요??

네~ 괜찮습니다~ 작성자(제 Gtihub 링크 걸어서)만 맨 위에 적어주세요.

**Comment by JSY8869** [comment]
> 네~ 괜찮습니다~ 작성자(제 Gtihub 링크 걸어서)만 맨 위에 적어주세요.

넵^^
