### ISSUE TITLE
Plan Issue에서의 Assignees 설정에 관한 질문입니다.

### ISSUE THREAD

**Issue by JSY8869** [JSY8869/Us-su#19]
# About Assignees
- 현재 매 주 Plan을 작성하여 Issue에 올리고 있고, 지금까지 모든 팀원을 Assignees로 설정해서 올려 왔는데 개인의 Plan에 대한 Issue에서 다른 인원을 Assignees로 설정하는 것이 맞는 것인지에 대해 의견을 듣고 싶습니다. 댓글로 적어주세요.
- 먼저 제가 생각하기에는 누군가의 도움이 필요한 경우이거나 협업을 하는 경우가 아닌 이상 Assignees로 설정하는 것은 틀리다고 생각합니다.

**Comment by parkwltn** [comment]
저도 Plan에 대한 Assignees는 설정하지 않는 게 맞는 것 같아요

**Comment by park-sohyeon** [comment]
저도 플랜 Assignees은 설정하지 않아도 된다고 생각합니당

**Comment by JSY8869** [comment]
과반수가 동의했으니 앞으로 Plan 관련 Issue는 Assignees는 자기 자신만 설정하는 것으로 합시당~~
