### ISSUE TITLE
팀명 정하기

### ISSUE THREAD

**Issue by JSY8869** [JSY8869/Us-su#2]
# 의견 주세요ㅠㅠ

**Comment by JSY8869** [comment]
# SUS4
## 각자 이름의 한 글자를 이용함
`S`uHyeok
JiS`u`
`S`eYoung
`S`ohyeon
## 의미
- suspended의 줄임말로 악보에서 걸림음을 뜻한다.
 - So, U,Special의 함축어로 함께하는 모든 사람들이 특별하다는 의미를 가지고 있다.

**Comment by park-sohyeon** [comment]
Us-su

> 이름 안에 있는 u,s 조합

> ‘우리’가 ‘우수’한 성적을 거둘 것이라는 뜻

**Comment by park-sohyeon** [comment]
### Us-su

### 의미
1. 각자 이름에 있는 u,s 조합
2. '우리'가 '우수'한 성적을 거둘 것이라는 의미

**Comment by park-sohyeon** [comment]
### Us-us

### 의미
1. 각자 이름에 있는 u,s 조합
2. '우리'가 '우수'한 성적을 이룰 것이라는 의미

**Comment by park-sohyeon** [comment]
> ### Us-su
> ### 의미
> 1. 각자 이름에 있는 u,s 조합
> 2. '우리'가 '우수'한 성적을 이룰 것이라는 의미
