### ISSUE TITLE
NPO 조사

### ISSUE THREAD

**Issue by park-sohyeon** [JSY8869/Us-su#23]
우선 NPO는 비영리 민간단체입니다. e-나라지표에서 중앙행정기관에 등록된 npo들은 1600여개가 됩니다. 그 중 이용자들이 기부와 후원을 주로 할 수 있는 단체를 찾았습니다. 대체적으로 단체들이 기부의 의미보다 자신의 단체를 후원해 달라는 내용입니다. 

npo단체들의 후원은 다음과 같은 단체들과 비슷한 방식으로 운영되고 있습니다.

### 1. 한국소비자연맹 - (소비자 권익보호를 위해 소비자 피해나 불만에 대한 소비자상담 중재 처리, 이슈에 따른 소비자교육, 불공정거래관행에 대한 실태조사 등을 수행)
> 정기후원으로 이루어지고 있으며 1년을 주기로 업데이트 됨. 전반적으로 한국소비자연맹이 활동하는 것을 지원하는 기부금임. 해피빈으로 모금. 

### 2. 평화의 집-(탈북자들의 권익과 복리증진, 정신문화고양,평화통일연대사업 등)
> 정기후원의 방식(1. 일반후원- 시설 및 재단의 일반적인 사업 후원, 2. 결연후원-아동과 1:1로 결연을 맺는 후원, 3. 물품후원 - 아동들에게 필요한 물품을 통한 후원)
*주기적으로 업데이트 x, 인터넷 후원신청서 작성을 통한 직접적인 계좌를 통한 기부

### 3. 국제사랑재단 - (민간차원의 대북 인도적  지원 등)
> 정기후원, 일시후원으로 나뉨. 주기적 업데이트 x

### 4. 메디피스 - (긴급구호,보건의료,개발교육)
> 정기후원, 일시후원으로 나뉨. 주기적 업데이트 x

npo는 ngo에 비해 정기후원의 방식이 많으며 그렇다보니 주기적으로 업데이트가 안됨.
후원은 단체의 전반적인 활동을 지원하는 방식으로 통일, 소비자 권리, 독립운동가, 독도, 저소득층, 국가안보 등 민간단체들이라 주된 사업이 다양함.

1600여개 npo기구들
http://www.index.go.kr/potal/main/EachDtlPageDetail.do?idx_cd=2856

**Comment by fora22** [comment]
# 제가 아는 NGO 추가
Topic이 정해졌는지 모르겠지만 NPO에 관한 이슈가 보이길래 잠깐 코멘트 하겠습니다. 이슈 제목은 NPO에 관한 것이지만 일반적으로 NGO는 NPO의 하위 개념으로도 보기 때문에, NGO에 대한 이야기여도 감안하고 들어주세요.

간단히 말하면 제가 후원하고 있는 2개 단체를 홍보(?) 겸 소개시켜드릴려고 합니다.

# [생명의 숲](https://forest.or.kr/)
> 시민과 함께 건강한 숲, 지속가능한 사회를 만들어가는 시민단체(NGO)다. 1998년 3월 18일, 생명의 숲가꾸기를 통해 건강한 사회를 만들고자 창립하였다. 숲 가꾸기 운동을 시작으로 현재는 숲문화운동, 도시 숲 운동, 학교 숲 운동, 정책운동 등 다양한 영역에서 숲 운동을 펼치고 있다. - [위키백과](https://ko.wikipedia.org/wiki/%EC%83%9D%EB%AA%85%EC%9D%98%EC%88%B2%EA%B5%AD%EB%AF%BC%EC%9A%B4%EB%8F%99)

생명의 숲은 환경과 관련된 활동을 하는 NGO입니다. 대부분은 숲과 관련된 활동으로 학교나 도시에 숲을 만드는 활동과, 숲을 보존하는 활동 등을 하고 있습니다. 꾸준하게 활동 및 업데이트도 하고 있고, [정기 후원제도](https://forest.or.kr/pages/11)도 진행하고 있습니다. 

# [플라스틱 방앗간](https://ppseoul.com/mill) - [서울 환경 연합](http://ecoseoul.or.kr/)

> 서울환경연합은 생명·평화·생태·참여의 가치를 향해
풀뿌리 환경보호 활동을 하는 NGO(비영리시민단체)입니다. - [서울환경연합 단체 소개](http://ecoseoul.or.kr/%eb%b9%84%ec%a0%84)

서울환경연합은 서울시의 생태환경에 관한 이슈에 대해 목소리를 내는 단체입니다. 

저는 '플라스틱 방앗간' 이라는 단체의 프로젝트를 통해 이 단체를 알게 되었습니다([설명영상 1 - 스브스 뉴스](https://youtu.be/0eougPjZrd8) , [설명영상 2 - 스브스 뉴스](https://youtu.be/X2i9oZ5na3k)).
사실 저는 서울 시민이 아니라 이 단체는 별로 관심이 많지 않지만 프로젝트 내용이 너무 맘에들어서 후원하고 있습니다.

[후원](https://happybean.naver.com/donations/H000000174744)은 네이버 해피빈을 통해 할 수 있습니다.


# 혹시 회의록은 작성하고 계신가요?

괜한 참견일수도 있습니다. 감안해서 들어주시길 바랍니다.

여러분 미팅 이슈는 지속적으로 올라오는거 보니 미팅은 하고 있는 것 같은데 회의록은 따로 작성하여 저장해두시나요? 만약 작성하고 있다면 다행입니다. 

하지만 작성하지 않고 있다면 이후에 문제가 생길 수도 있습니다. 지금은 회의 횟수가 한 손으로 셀 수 있으니 무슨 내용을 얘기했는지 기억이 나지만, 점점 가면 갈수록 이전 회의 내용은 잊혀집니다.

특히 Plan을 적을 때면 자신이 무엇을 해야할지 회의 때 정했지만 기억이 안나는 경우도 있을 수 있습니다. 그래서 회의록을 쓰는게 좋지 않을까 라는 생각이 듭니다.

## 회의록의 이점
1. 회의의 증거자료
   - 이후 공모전 혹은 설계 수업 때 회의를 했다는 증거 자료가 됩니다.
   - 사실 회의록 말고는 회의의 증거자료가 있을 수 없습니다.
2. 이후 진행방향에 대한 이정표
  - 이전에 진행방향에 대해 정리해놓았다면 이후 진행에 있어 큰 밑거름이 됩니다. 
  - 만약 정리하지 않았다면 팀원간에 진행방향에 대한 방향성이 다를 수 있습니다. (서로 잘못 기억해서)

## 참고할 만한 회의록 양식
제 팀은 현재 회의록을 작성하고 Meeting Issue에도 올리고 notion 회의록에도 올리고 있습니다. 그래서 내용을 잠깐 공유해드리려고 합니다.

회의록 작성자는 보통 원하는 사람(정리하고 싶은 사람)이 적습니다. 그래야 문서가 잘 작성되기 때문입니다(제가 한 말은 아니고 어느 분 께서 하신 말씀입니다). 

- [8th](https://github.com/JEoN-Ha/Senior-Project/issues/60#issuecomment-758065026)
- [7th](https://github.com/JEoN-Ha/Senior-Project/issues/47#issuecomment-754415690)
- [6th](https://github.com/JEoN-Ha/Senior-Project/issues/36#issuecomment-751599457)
- [5th](https://github.com/JEoN-Ha/Senior-Project/issues/32#issuecomment-748417522)
- [Notion](https://www.notion.so/fora22/Senior-Project-4d7262286f8f4aad855e05aa6e3f18d4) - 노션 링크는 1월 13일 이후로 닫을 예정입니다.

도움이 되면 좋겠습니다.

**Comment by JSY8869** [comment]
# NGO에 관하여
사실 NGO에 관해서 제가 조사 하기로 했는데 아직 조사를 완료하지 못했습니다. 오늘 하려고 했는데 좋은 정보 감사합니다!ㅎㅎ
# 회의록에 관하여
회의록의 경우 이미 이야기를 했었는데, 현재 하고있는 아이디어 회의가 끝난 이후부터 작성하는 것으로 정한 상태였습니다.(워낙 간단한 내용이었기 때문에)

사실 아이디어 회의의 경우에도 회의록이 필요하다는 생각을 하고 있었습니다. 좋은 의견 감사드리고 Issue를 통해서 회의록을 작성하는 방향으로 회의를 진행해 보겠습니다!
