### ISSUE TITLE
순서도

### ISSUE THREAD

**Issue by su-hyeok** [JSY8869/Us-su#63]
![순서도1](https://user-images.githubusercontent.com/64292838/108328535-13133080-7210-11eb-9e68-151e254da2aa.PNG)

![순서도2](https://user-images.githubusercontent.com/64292838/110103208-059d9f00-7de9-11eb-915d-b5bd6e07e087.PNG)

![순서도3](https://user-images.githubusercontent.com/64292838/108330556-122ece80-7211-11eb-9825-106abac758a5.PNG)

**Comment by JSY8869** [comment]
일기장 읽기, 수정 기능만 추가해주고 일단 마무리하면 될듯!

**Comment by su-hyeok** [comment]
수정완료!
