### ISSUE TITLE
APP 내 게임 변경에 관한 의견

### ISSUE THREAD

**Issue by parkwltn** [JSY8869/Us-su#64]
저번 주 회의에서 게임을 카드 뒤집기와 동물 세기로 정했지만 다른 치매 어플들을 조사해보고 이야기를 나눠봤으면 해서 이슈 올립니다.

저희 치매 예방 프로그램의 주 기능은 **일기장 작성 > 퀴즈 풀기** 인데요.
카드 뒤집기와 동물 세기 게임은 일기장 컨셉과 동떨어져 있다고 느꼈고, 다른 치매 예방 어플들의 게임과 비교해봤을 때 차별성이 없어 경쟁력을 갖기 힘들다고 생각됩니다...

따라서 저는 
1. **게임을 다 빼고 일기장에만 집중해서 일기장 퀴즈를 세분화**

하거나 

2. **추억 컨셉으로 기존 어플들에 없는 게임을 추가**

했으면 하는데요.

다른 분들의 의견을 듣고 싶습니다.

2의 경우, 예시는 **그때를 기억하시나요**로, 중앙치매센터에서 제공하는 치매 예방 게임입니다. 
어플로 제작된 것은 아니고, 수기로 작성하도록 자료를 공유한 것을 참고했습니다.

**설명**
누구나 기억할만한 과거 신문 기사나 광고 상의 그림 또는 사진 및 회상 시 떠올려보아야 할 질문 5가지를 제공한다. 
사용자가 질문에 대한 답을 입력하면, 질문의 답을 저장하고 일기장 알고리즘을 사용하여 새 질문을 만든다. 이후는 일기장과 동일. 
<img width="224" alt="그때를 기억하시나요 1" src="https://user-images.githubusercontent.com/67677312/108484096-d2361d00-72de-11eb-9c75-ae083ee9e264.PNG">
[memory_yesterday.pdf](https://github.com/zsueue/Todo/files/6009019/memory_yesterday.pdf)

**Comment by JSY8869** [comment]
## 기존 의견
일단 카드 뒤집기와 동물 세기 게임의 경우는 일기장보다는 **치매예방**에 더 초점을 둔 부분이라고 생각합니다. 어떤 식으로 진행을 하던 시간이 남는다면 개발해서 나쁠것은 없다고 생각합니다.
## @zsueue 의 의견
**그때를 기억하시나요**의 경우 `누구나 기억할만한 과거 신문 기사나 광고 상의 그림 또는 사진 및 회상 시 떠올려보아야 할 질문`이라는 것에서 `누구나 기억할만한`이라는 조건이 가장 문제가 될 것 같네요. 큰 제한이 되지 않는다면 저는 @zsueue 님의 의견대로 가는 것이 좋아보입니다.

**Comment by parkwltn** [comment]
회의 결과
: 일기장, 그때를 기억하시나요 개발 후 시간이 남으면 게임 추가!
