### ISSUE TITLE
핵심어 추출 관련 의견

### ISSUE THREAD

**Issue by su-hyeok** [JSY8869/Us-su#65]
자연어처리를 하여 핵심 단어를 찾는것이 하나로 정형화 되어 있지 않기 때문에 의견을 들어보려 합니다.
사이트 주소를 넣어 줄테니 회의 때 서로의 의견을 내는것이 좋을듯 합니다.

**사이트 주소**
- https://github.com/konlpy/konlpy
- https://github.com/lovit/KR-WordRank
- https://github.com/lovit/textrank

**추가**
이미 만들어져있는 프로그램을 사용할 것인가?
이외의 것들도 찾으면 회의 때 설명해드립니다

**Comment by JSY8869** [comment]
## 알고리즘 선택
각 알고리즘의 장점, 단점, 할수있는 분야를 정리해보고 판단하는 것이 좋을것 같네요. 
## 기존의 프로그램 사용에 관하여
물론 직접 개발해서 사용하는 것이 가장 좋겠지만 우리가 중점적으로 생각해야할 부분은 기존의 프로그램을 어떤 목적을 가지고 어떻게 활용해서 어떤 결과물이 나왔는지가 더 중요하다고 생각합니다.
