### ISSUE TITLE
교수님 면담 시 질문할 것!

### ISSUE THREAD

**Issue by JSY8869** [JSY8869/Us-su#69]
1. 교수님께 아이디어 결정된 것 말씀 드리고, 순서도 및 각자 역활 분담한 것, 진행상황 보고 해주기 바람
2. Kotlin으로 개발할 것이라고 보고 바람
3. 게임은 어떤 언어가 좋고, Kotlin으로 개발한 UI에 다른 언어로 개발한 게임을 넣을 수 있는지 질문
4. DB내의 일기장의 내용을 가져와 Python으로 작성된 자연어 처리 알고리즘으로 처리한 후 문장을 만들어서 게임에 넣을 수 있는지 질문
5. DB의 경우 어떤 언어로 개발하는 것이 좋은지 질문

**Comment by JSY8869** [comment]
추가로 각자 궁금한 것 추가 바람

**Comment by parkwltn** [comment]
1. 처음 기획처럼 대상을 50대 이상으로 정하고 앱을 개발하는 것이 좋을지, 대상을 넓게 잡고 개발하는 것이 좋을지.

**Comment by su-hyeok** [comment]
1,2번 보고드림
3,4번의 경우 다른언어를 사용한 후 적용 시킬수는 있지만 배보다 배꼽이 더 커질것으로 생각된다 하심
그렇게 할거면 웹사이트에서 어플리케이션으로 끌어오는 웹뷰를 사용해야한다고 하심. 
어느 경로로던 할수는 있으니 그건 우리 선택에 맡기셨고 5번의 경우도 마찬가지의견.
지수 질문은 어떤것이던 상관 없다고 하심
교수님께 모든 상황 보고드렸을 때 하신 말씀이 어렵겠다 + ui 쪽 맡은 지수가 빨리 ui를 완성시키고 게임이던 핵심어던 도와줘야한다고 말씀하심. 
따라서 우리끼리의 회의를 통해 정해야할 것 같다는 것이 내 의견
참고로 나는 파이썬으로 형태소 분석중이고, 파이썬이 아닌 자바로도 형태소 분석 즉 핵심어 추출을 할 수 있다고 말씀하심
오늘 면담의 결과는 여기까지입니다
