### ISSUE TITLE
Idea 관련 제안입니다.(시나리오 작성, 결과 제공 화면)

### ISSUE THREAD

**Issue by parkwltn** [JSY8869/Us-su#73]
## 시나리오 작성
현재 순서도에는 메인 기능(일기장, 게임)에 대해서만 작성되어 있는데요. 어플 개발 전에 처음~끝까지 사용자가 앱을 사용하는 순서대로 시나리오를 작성해보면 좋을 것 같습니다! 이전에 교수님께서 말씀하신 스토리 보드와 비슷한 개념입니다.
> 예를 들어 출퇴근 날씨 어플이라면, 사용자가 앱을 다운로드 받고 설치한다. 로그인을 하고 출퇴근 지역과 시간을 설정한다. 출퇴근 1시간 전에 푸쉬알림으로 날씨 정보를 보여준다. 알림 팝업을 터치하면 상세 날씨 정보를 보여준다.

**스토리 보드**
- 어떠한 방향으로 프래그래밍이 진행될 건지에 대한 정리
- 화면 구성/기능/등등...
### 순서도에 없는 나머지 화면들
어플 실행시 뜨는 화면, 회원가입, 로그인, 설정 화면, 게임 직후 결과 제공 화면, 이전 결과와 비교 화면 등등
## 결과 제공 화면에 대하여
게임이 끝난 직후 사용자에게 어떤 결과를 제공할건지도 생각해봤으면 합니당.
게임의 수가 많은 타 어플들은 5가지 인지 영역(기억/언어/지각/사고/주의)에 대한 그래프로 결과를 제공하는데요.
우리 치매 예방 프로그램은 게임의 수가 적고, 5가지 인지 영역에 대한 그래프를 제공하기엔 무리가 있어 보입니다. (기억력과만 관련있다고 생각합니다...)
## 추가적으로...
Wiki에 [어플리케이션 제작 과정](https://github.com/JSY8869/Us-su/wiki/%EC%96%B4%ED%94%8C%EB%A6%AC%EC%BC%80%EC%9D%B4%EC%85%98-%EC%A0%9C%EC%9E%91-%EA%B3%BC%EC%A0%95)을 잘 정리한 글이 있어서 올려두었는데요. 읽어보시면 좋을 것 같습니당~

**Comment by JSY8869** [comment]
좋은 의견이네용 다음 회의때 참고할게요~

**Comment by parkwltn** [comment]
넹~
