### ISSUE TITLE
게임 디자인 프로그램 방향성

### ISSUE THREAD

**Issue by park-sohyeon** [JSY8869/Us-su#74]
게임 디자인
1. [유니티 2d 버전](https://m.blog.naver.com/PostView.nhn?blogId=fightingdog&logNo=220034264831&proxyReferer=https:%2F%2Fwww.google.com%2F)으로 만들고
2.  안드로이드 스튜디오에 [연동](https://hub1234.tistory.com/28)시키기

여기서 문제가 유니티는 자바와 C#만을 지원함.
그리고 참고자료가 C#이 많음.

유니티 말고 DEFOLD 나 언리얼 엔진4 등 프로그램이 더 있긴 한데 한글 자료가 많이 없고 안드로이드 스튜디오 연동하는 정보가 안 나옵니다.

2D 게임을 만드는 프로그램을 알아보았는데  
제가 지금 올바른 방향으로 알아보고 있는게 맞나요??

**Comment by JSY8869** [comment]
언리얼 엔진같은 경우는 너무 어려워서 불가능하고, 유니티는 기본적으로 그냥 C#으로 한다고 보는게 맞다고 알고있음

어차피 C#이라고 문법이 많이 다른것도 아니니까 유니티랑 같이 차근차근 공부하는게 가장 좋아보임
