### ISSUE TITLE
Kotlin 앱 개발 예시

### ISSUE THREAD

**Issue by JSY8869** [JSY8869/Us-su#86]
Kotlin으로 캘린더를 만든 예시인데 활용해서 일기장 화면을 만들면 좋겠다 싶어서 올립니다~

https://newseoul.tistory.com/143?category=788541

**Comment by parkwltn** [comment]
확인했습니다!
- 예시
할 일 목록 표시 화면에서 할 일 추가 버튼 클릭하면 편집(달력) 화면으로 이동. 편집 화면에서 작성/수정/삭제
- 순서도
달력 화면에서 날짜 선택하면 작성 화면으로 넘어감. 작성 화면에서 작성/수정/삭제
